# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('com', 'house of commons'), ('lrd', 'house of lords')], max_length=3)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.Session'),
        ),
        migrations.AddField(
            model_name='blockquote',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.Debate'),
        ),
        migrations.AddField(
            model_name='blockquote',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.Speaker'),
        ),
    ]
