# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
