# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0003_auto_20180122_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='hansardscraper.Session'),
        ),
    ]
