# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 14:19
from __future__ import unicode_literals
from django.db import migrations, models
from django.contrib.postgres.operations import UnaccentExtension
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0004_auto_20180122_1257'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),

    ]

