# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0006_searchquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='quotes',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
