# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0007_auto_20180128_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.SearchQuery')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.BlockQuote')),
            ],
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results',
            field=models.ManyToManyField(blank=True, null=True, through='hansardscraper.QueryParams', to='hansardscraper.BlockQuote'),
        ),
    ]
