# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0009_auto_20180128_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='date',
            new_name='started',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
