# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0010_auto_20180307_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimitiveQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimitiveQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('usefull', models.NullBooleanField(default=None)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hansardscraper.PrimitiveQuery')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.BlockQuote')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=200)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleQueryParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.SimpleQuery')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.BlockQuote')),
            ],
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='results',
        ),
        migrations.AlterField(
            model_name='queryparams',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansardscraper.Query'),
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
        migrations.AddField(
            model_name='simplequery',
            name='results',
            field=models.ManyToManyField(blank=True, through='hansardscraper.SimpleQueryParams', to='hansardscraper.BlockQuote'),
        ),
        migrations.AddField(
            model_name='simplequery',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_query', to='hansardscraper.Search'),
        ),
        migrations.AddField(
            model_name='query',
            name='results',
            field=models.ManyToManyField(blank=True, through='hansardscraper.QueryParams', to='hansardscraper.BlockQuote'),
        ),
        migrations.AddField(
            model_name='query',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='hansardscraper.Search'),
        ),
        migrations.AddField(
            model_name='primitivequery',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primitive_query', to='hansardscraper.Search'),
        ),
    ]
