# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansardscraper', '0011_auto_20180401_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primitivequeryresult',
            old_name='usefull',
            new_name='useful',
        ),
        migrations.AddField(
            model_name='blockquote',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blockquote',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debate',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debate',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
