# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added_on', models.DateField(auto_now=True)),
                ('year_of_birth', models.DateField()),
                ('year_of_death', models.DateField(blank=True)),
                ('branch', models.CharField(max_length=255)),
                ('nationality', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person_tracker.Nationality')),
            ],
        ),
    ]
