# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0002_person_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='fake', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='middlename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
