# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0003_auto_20171105_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
