# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0004_auto_20171105_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_tracker.Nationality'),
        ),
    ]
