# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0006_auto_20171111_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
    ]
