# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0011_auto_20171112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='person_tags', to='notes.Tag'),
        ),
    ]
