# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_tracker', '0014_auto_20171210_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
