# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20171112_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ttag',
        ),
        migrations.AddField(
            model_name='note',
            name='ttag',
            field=models.ManyToManyField(blank=True, null=True, to='notes.Tag'),
        ),
    ]
