# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20171112_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='ttag',
            new_name='tags',
        ),
    ]
