# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20171112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='note_tags', to='notes.Tag'),
        ),
    ]
