# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_tracker', '0003_auto_20171105_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_city',
            field=models.CharField(default='Amsterdam', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(default='fred', max_length=255),
            preserve_default=False,
        ),
    ]
