# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_tracker', '0004_auto_20171111_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pamphlet',
            name='notes',
        ),
    ]
