# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20171112_1934'),
        ('source_tracker', '0005_auto_20171111_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag'),
        ),
        migrations.AddField(
            model_name='pamphlet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag'),
        ),
    ]
