# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_tracker', '0006_auto_20171112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_tags', to='notes.Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='book_tags', to='notes.Tag'),
        ),
        migrations.AlterField(
            model_name='pamphlet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pamphlet_tags', to='notes.Tag'),
        ),
    ]
