# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_tracker', '0008_auto_20171113_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary')], default='SEC', max_length=3)),
                ('publisher_name', models.CharField(max_length=255)),
                ('publisher_city', models.CharField(max_length=255)),
            ],
        ),
    ]
