# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person_tracker', '0013_auto_20171113_2354'),
        ('notes', '0012_auto_20171209_2118'),
        ('source_tracker', '0009_reactbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary')], default='SEC', max_length=3)),
                ('source_class', models.CharField(choices=[('BO', 'Book'), ('AR', 'Article')], default='BO', max_length=3)),
                ('publisher_name', models.CharField(max_length=255)),
                ('publisher_city', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_tracker.Person')),
                ('tags', models.ManyToManyField(blank=True, related_name='source_tags', to='notes.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pamphlet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pamphlet',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pamphlet',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReactBook',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Pamphlet',
        ),
    ]
