# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_tracker', '0011_auto_20171210_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
